SELECT USER
FROM DUAL;
--==>> HR


--○ 세 개 이상의 테이블 조인(JOIN)

-- 형식1(SQL 1992 CONE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블2.컬럼명1
  AND 테이블명2.컬럼명1 = 테이블3.컬럼명2;

-- 형식2(SQL 1999 CONE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
        JOIN 테이블명3
        ON 테이블명2.컬럼명2 = 테이블3.컬럼명2;


--○ HR 계정 소유 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
--==>>
/*
COUNTRIES	        TABLE	
DEPARTMENTS	        TABLE	
EMPLOYEES	        TABLE	
EMP_DETAILS_VIEW	 VIEW	
JOBS	            TABLE	
JOB_HISTORY	        TABLE	
LOCATIONS	        TABLE	
REGIONS	            TABLE	
*/


--○ HR.JOBS, HR.EMPLOYEES, HR.DEPARTMENTS 테이블을 대상으로
--   직원들의 정보를 FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME     JOBS-JOB_TITLE EM-FI,LA DE-DEPANA
--   항목을 조회한다.


SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME
FROM JOBS, EMPLOYEES, DEPARTMENTS
WHERE JOBS.JOB_ID(+) = EMPLOYEES.JOB_ID
  AND EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+);
  

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME
FROM JOBS JOIN EMPLOYEES
ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
        LEFT JOIN DEPARTMENTS
        ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT *
FROM JOBS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;


--○ EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS,COUNTRIES, REGIONS 테이블을 대상으로
--   직원들의 정보를 다음과 같이 조회한다.
--   FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
--   , CITY, COUNTRY_NAME, REGION_NAME

SELECT *
FROM REGIONS;

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM JOBS, EMPLOYEES, DEPARTMENTS, LOCATIONS,COUNTRIES, REGIONS
WHERE JOBS.JOB_ID(+) = EMPLOYEES.JOB_ID
  AND EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+)
  AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID(+)
  AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID(+)
  AND COUNTRIES.REGION_ID = REGIONS.REGION_ID(+);
  
  
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, JOBS.JOB_TITLE, DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM JOBS JOIN EMPLOYEES
ON JOBS.JOB_ID = EMPLOYEES.JOB_ID
        LEFT JOIN DEPARTMENTS
        ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
        LEFT JOIN LOCATIONS
        ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
        LEFT JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
        LEFT JOIN REGIONS
        ON COUNTRIES.REGION_ID = REGIONS.REGION_ID;































